cc_library(
    name = "hiredis",
    srcs = ["async.c","dict.c","hiredis.c","net.c","read.c","sds.c"],
    hdrs = ["async.h","dict.h","dict.c","fmacros.h","hiredis.h","net.h","read.h","sds.h","sdsalloc.h","adapters/ae.h","adapters/glib.h","adapters/ivykis.h","adapters/libev.h","adapters/libevent.h","adapters/libuv.h","adapters/macosx.h"],
    visibility = ["//visibility:public"],
)